AWSTemplateFormatVersion: "2010-09-09"
Description: ""
Parameters:
  AudioFileStore:
    Type: String

Resources:
  RxLambda:
    Type: AWS::Lambda::Function
    Properties:
      Code: ../../dist/local_lambdas.zip
      Handler: handlers.rx
      Role: !GetAtt DummyLambdaRole.Arn
      Runtime: python2.7
      Timeout: 300

  TxLambda:
    Type: AWS::Lambda::Function
    Properties:
      Code: ../../dist/local_lambdas.zip
      Handler: handlers.tx
      Role: !GetAtt DummyLambdaRole.Arn
      Runtime: python2.7
      Timeout: 300

  DummyLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
          Action:
          - sts:AssumeRole

Outputs:
  RxLambda:
    Value: !Ref RxLambda

  TxLambda:
    Value: !Ref TxLambda
