---
AWSTemplateFormatVersion: '2010-09-09'
Description: "Provision the Talko-Lingo's service"

Resources:
  AudioFileStore:
    Type: AWS::S3::Bucket
    DeletionPolicy: Delete

  SNSTopic:
    Type: AWS::SNS::Topic
    Properties:
      Subscription:
      - Endpoint: !GetAtt LocalLambdas.Outputs.TxLambdaArn
        Protocol: lambda

  LocalLambdas:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: local-lambdas.yml
      Parameters:
        AudioFileStore: !Ref AudioFileStore

Outputs:
  RxLambda:
    Value: !GetAtt LocalLambdas.Outputs.RxLambda

  TxLambda:
    Value: !GetAtt LocalLambdas.Outputs.TxLambda
