---
AWSTemplateFormatVersion: '2010-09-09'
Description: "Provision the Talko-Lingo's Transcribe service"

Resources:
  TalkoLingoWebsiteBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Delete
    Properties:
      NotificationConfiguration:
        LambdaConfigurations:
        - !Ref AWS::NoValue        #Entrypoint to AWS Transcribe Step Functions
